ruby-hl7/ruby-hl7

- .travis.yml
- lib/message.rb
- lib/segments/obx.rb
- spec/message_spec.rb
- spec/obx_segment_spec.rb
Fixes #51 
The idea is to have a `correction?` method that you can call on the HL7 message or the OBX segment.
Thanks @clausti and @adamstegman for the feedback and the initial idea.
> Adding "correction?" method to HL7 message and OBX segment

- lib/segments/sft.rb
- spec/sft_segment_spec.rb
Removing the set id from the SFT segment.  It does not exist in the HL7 specifications version 2.5.1 or in any other reference I could find online.
http://hl7-definition.caristix.com:9010/Default.aspx?version=HL7%20v2.5.1&segment=SFT
https://www.mnhospitals.org/Portals/0/Documents/data-reporting/ahrq/implementation_guide_elab_rptg.pdf
> Update the SFT Segment

- lib/segment.rb
- spec/segment_spec.rb
Make segments enumerable on their elements. Added test to compare enumerable elements with segment.length.
Issue: https://github.com/ruby-hl7/ruby-hl7/issues/55
> Enumerable elements from segment

- lib/segments/mfe.rb
- lib/segments/mfi.rb
- lib/test/hl7_messages.rb
- spec/messages_spec.rb
- spec/mfe_segment_spec.rb
- spec/mfi_segment_spec.rb
Adding support for MFN^M13 type messages.  This at minimum requires two additional segments: MFE and MFI.
Additionally, I leveraged the existing ```hl7_messages.rb``` file to test messages integration.  
http://hl7-definition.caristix.com:9010/HL7%20v2.3/segment/Default.aspx?version=HL7+v2.5.1&segment=MFI
http://hl7-definition.caristix.com:9010/HL7%20v2.3/segment/Default.aspx?version=HL7+v2.5.1&segment=MFE
> Adding MFE and MFI Segments

- lib/segment_fields.rb
- spec/segment_field_spec.rb
Add an array accessor to segments.  Useful when the segment is not defined so named accessors are not an option.
> Segment element array accessor

- lib/segments/dg1.rb
- spec/dg1_spec.rb
Added diagnosis_description (DG1.4) per the HL7 Docs here: http://hl7-definition.caristix.com:9010/HL7%20v2.3.1/segment/DG1
Before, date_time (DG1.5) was being used to gather description information and all other fields were being offset by 1.
> Add diagnosis_description to DG1 per HL7 Docs

- lib/message.rb
- lib/segment_fields.rb
Ruby 2.4.0 unifies the Fixnum and Bignum classes into Integer, and so Fixnum is deprecated. 
See here: https://bugs.ruby-lang.org/issues/12005
> Replace Fixnum with Integer

- Gemfile
- Rakefile
- ruby-hl7.gemspec
RubyForge is only used in Rakefile.
However, rubyforge gem is not under maintenance.
I think dependency on rubyforge gem should be deleted in the next step.
Thank you.
> Move rubyforge gem to development dependencies from runtime dependencies

- lib/segments/sch.rb
- spec/sch_segment_spec.rb
Adding a standard segment SCH for Schedule Activity Information.
http://hl7-definition.caristix.com:9010/HL7%20v2.3.1/segment/SCH
> Add SCH segment

- lib/segments/ail.rb
- spec/ail_segment_spec.rb
Adding the standard AIL segment (Appointment Information - Location Resource) for use in scheduling message integration.
http://hl7-definition.caristix.com:9010/HL7%20v2.3.1/segment/AIL
> Add AIL segment to ruby-hl7

- lib/segments/aig.rb
- lib/segments/ail.rb
- lib/segments/ais.rb
- lib/segments/mrg.rb
- lib/segments/rgs.rb
- lib/segments/sch.rb
- lib/segments/tq1.rb
Hi,
This PR add 5 standard segments and add 2 fields into SCH segment.
I have used HL7 v2.5.1 for the fields names.
New segments:
* [AIG](http://hl7-definition.caristix.com:9010/Default.aspx?version=HL7%20v2.5.1&segment=AIG)
* [AIS](http://hl7-definition.caristix.com:9010/Default.aspx?version=HL7%20v2.5.1&segment=AIS)
* [MRG](http://hl7-definition.caristix.com:9010/Default.aspx?version=HL7%20v2.5.1&segment=MRG)
* [RGS](http://hl7-definition.caristix.com:9010/Default.aspx?version=HL7%20v2.5.1&segment=RGS)
* [TQ1](http://hl7-definition.caristix.com:9010/Default.aspx?version=HL7%20v2.5.1&segment=TQ1)
New fields on SCH ([reference](http://hl7-definition.caristix.com:9010/Default.aspx?version=HL7%20v2.5.1&segment=SCH)):
* SCH.26 placer_order_number
* SCH.27 filler_order_number
(And also fixed …
> Add AIG, AIS, MRG, RGS, TQ1 segments and add fields on SCH

- lib/segments/in1.rb
- spec/in1_segment_spec.rb
Adding fields to the IN1 segment for use sending parent insurance carrier.
http://hl7-definition.caristix.com:9010/Default.aspx?version=HL7+v2.5.1&table=0099
> Adding fields to IN1 segment

- README.rdoc
Hi,
The ZCF segment has been deleted in #85. As recommended by @mogox, this PR adds a migrating section into the README.
> Add ZCF deletion notes to README

- lib/segments/pid.rb
- spec/pid_segment_spec.rb
The HL7 2.x specification defines PID-12 as County/Parish Code, but the gem names the field `:country_code`. I included a deprecation warning here to avoid confusion, but the name could also be aliased silently via `alias_field`.
> Rename PID-12 from 'country_code' to 'county_code' per specification

- Gemfile.lock
- ruby-hl7.gemspec
Noticed that Ruby-HL7 was forcing consumers to use a different rake version; I don't _think_ that's necessary so opting to change it (and rdoc).
> change rake and rdoc to dev dependencies

- spec/pid_segment_spec.rb
Just a tiny validation test case removal, mentioned [here](https://github.com/ruby-hl7/ruby-hl7/pull/128#discussion_r1787660401).
> chore: remove 'C' value from PID segment validation spec

- .github/workflows/test.yml
- Gemfile.lock
- ruby-hl7.gemspec
This PR adds a 'Github Actions' CI workflow, running the project RSpec test suite on a panel of Ruby versions, as mentioned in [this comment](https://github.com/ruby-hl7/ruby-hl7/pull/124#issuecomment-2393688053) by @Stratus3D .
_Note: This PR simply adds an arbitrary minimal CI config; I intend to add some relevant workflows (rubocop at least, for a start) in upcoming PRs_
> Chore: Add first Github Action for Rspec workflow

- lib/segments/prt.rb
- spec/prt_segment_spec.rb
The current PR adds support for the HL7 `PRT` segment, as introduced in HL7 version 2.7, following this specification:
https://hl7-definition.caristix.com/v2/HL7v2.8/Segments/PRT
> Feat: Define PRT segment

- lib/helpers/time_formatter_helper.rb
- lib/ruby-hl7.rb
- lib/segment.rb
- lib/segments/dg1.rb
- lib/segments/prt.rb
- spec/helpers/time_formatter_helper_spec.rb
- spec/spec_helper.rb
Historically, HL7-related date-formatting was done with the help of a [monkey-patch](https://github.com/ruby-hl7/ruby-hl7/blob/eb69e499b288056d08ad3a347874e42d632eec76/lib/core_ext/date_time.rb#L3) of `Date`, `DateTime` and `Time` classes that defines a custom `to_hl7` method to them.
This PR introduces a helper for this exact purpose and replaces usages of the monkey-patched methods throughout the gem's codebase.
In a further PR, I suggest we deprecate the `to_hl7` methods and add instructions to the README on how to use these helpers instead.
* chore: Add new helper TimeFormatterHelper defining formatting methods for time objects
* chore: load new helper globally, add extend statement in HL7::Message::Segment
* chore: (HL7::Message::Segment) Update .convert_to_ts method to use …
> Chore: Add helpers for date-formatting

- lib/segments/pv2.rb
- spec/pv2_segment_spec.rb
This PR brings one fix and several small improvements to the `PV2` segment:
- add missing `admission_level_of_care_code` field (originally breaking the order of the subsequent fields)
- streamline the way we define fields
- add a proper spec file
- fix a typo on `military_non_availibility_code`, while keeping it backward-compatible
> Chore: Various PV2 segment improvements

- lib/segment.rb
- lib/segments/gt1.rb
- lib/segments/nk1.rb
- lib/segments/pid.rb
- spec/nk1_segment_spec.rb
The current PR adds support for the HL7 `NK1` segment in its version 2.8, following this specification:
https://hl7-definition.caristix.com/v2/HL7v2.8/Segments/NK1. This work was initiated in [this PR](https://github.com/ruby-hl7/ruby-hl7/pull/125) but never finished.
The current PR also factors out a bit of duplicate validation logic shared between multiple segments.
> Feat: Define missing fields to NK1 segment

- lib/segments/rol.rb
- spec/rol_segment_spec.rb
The current PR adds support for the HL7 `ROL` segment in its version 2.8, following this specification:
https://hl7-definition.caristix.com/v2/HL7v2.8/Segments/ROL
> Feat: Implement ROL segment
